### PR TITLE
fix #37, allow resending an unexpired token

### LINKED ISSUE #37: Allow creation of a new token even if an already still valid token exists
Hi :)

Currently (unless I missed a config option), we can’t ask for a new token if a token has already been asked and still valid regarding its age.

I wonder why this restriction.

As a user, I would rather (and I think it’s what the majority of websites do) be able to ask for a new token even if one exists (invaliding the former one in the process).

The most evident use case I’m thinking of is the email with the token being never received.

If it’s for security reason because hashing is cpu consuming, we could set a delay minimum of a few seconds that would be sufficient in this regard I reckon.

### PR DESCRIPTION
**Pull request by gorghoa**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #37
| License       | MIT

Hi @vincentchalamon :)

This PR removes the `UnexpiredTokenHttpException` in favour of resending the already existing token.

### CODE REVIEW

**Comment by gorghoa** [comment]
wait, I forgot the behat tests…

**Comment by vincentchalamon** [comment]
Hi @gorghoa, thanks for this PR :-)
Sadly, I cannot merge it until tests are green. Maybe this error (about `twig.controller.exceptioin`) reveals a dependency error, or a bug in this PR code. You must fix it in order to merge this PR.

**Comment by gorghoa** [comment]
I understand. Actualy, it fails on master too :/

**Comment by gorghoa** [comment]
waiting for #42

**Comment by vincentchalamon** [comment]
@gorghoa #42 merged, you can rebase

**Comment by gorghoa** [comment]
w00t w00t, thanks @vincentchalamon, all good now :)

**Comment by vincentchalamon** [comment]
Thanks @gorghoa :heart:
I'll tag a new release in a few minutes

**Pull request merged**
